### ISSUE TITLE
Exception: Response status code: 401

### ISSUE THREAD

**Issue by Pablohn26** [outscraper/google-services-api-pyhton#1]
Using the main example I am getting a 401 error

```
./main.py              [25/02/21| 2:08]
Traceback (most recent call last):
  File "./main.py", line 11, in <module>
    business_with_reviews = api_cliet.google_maps_business_reviews('Memphis Seoul brooklyn usa', limit=100, language='en')
  File "/home/foo/google-services-api-pyhton/outscraper/api_client.py", line 153, in google_maps_business_reviews
    raise Exception(f'Response status code: {response.status_code}')
Exception: Response status code: 401

```

I am using Google API REST and the same API KEY is working, so I do not know the reason

**Comment by vlad-outscraper** [comment]
> I am using Google API REST...

@Pablohn26 Do you mean you're using the Google API key for the SDK?
Please get the API key from Outscraper https://app.outscraper.com/profile in order to use this SDK.
![Screen Shot 2021-03-09 at 11 35 44 PM](https://user-images.githubusercontent.com/60986120/110597282-02a80300-8189-11eb-8600-0b0a2b90ea99.png)

**Comment by Pablohn26** [comment]
Oh sorry I meant Google key, I did not realize that. Thanks
